version: 0.0
os: linux
files:
  - source: /apache2
    destination: /var/www/html/apache2
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/set_permission.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root
