version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/apache2
hooks:
  AfterInstall:
    - location: scripts/set_permission.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_apache.sh
      timeout: 300
      runas: root
